site_name: SJTU Course Notes
site_description: Course notes from Shanghai Jiao Tong University
site_author: youyeyejie
repo_url: https://github.com/youyeyejie/SJTUnotes
edit_uri: edit/main/docs/
theme:
  name: material
  language: zh
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer   # 开启底部上一篇/下一篇导航
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# 额外配置
extra:
  generator: true  # 隐藏"Made with Material for MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/youyeyejie
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # 替换为您的Google Analytics ID

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
#   - assets/javascripts/katex.js
#   - https://unpkg.com/katex@0.16.8/dist/katex.min.js
#   - https://unpkg.com/katex@0.16.8/dist/contrib/auto-render.min.js

extra_css:
  - assets/stylesheets/extra.css
#   - https://unpkg.com/katex@0.16.8/dist/katex.min.css

nav:
  - Home: index.md

  - CS0501-数据结构:
      - CS0501-数据结构/index.md
      - 引言: CS0501-数据结构/1.引言.md
      - 线性表: CS0501-数据结构/2.线性表.md
      - 栈: CS0501-数据结构/3.栈.md
      - 队列: CS0501-数据结构/4.队列.md
      - 树: CS0501-数据结构/5.树.md
      - 优先级队列: CS0501-数据结构/6.优先级队列.md
      - 集合和静态查找表: CS0501-数据结构/7.集合和静态查找表.md
      - 动态查找表: CS0501-数据结构/8.动态查找表.md
      - 排序: CS0501-数据结构/9.排序.md
      - 外部查找与排序: CS0501-数据结构/10.外部查找与排序.md
      - 图: CS0501-数据结构/11.图.md
  - CS2501-离散数学:
      - CS2501-离散数学/index.md
      - 图论: 
        - 基本概念: CS2501-离散数学/1.1.基本概念.md
        - 道路与回路: CS2501-离散数学/1.2.道路与回路.md
        - 树: CS2501-离散数学/1.3.树.md
      - 数理逻辑: 
        - 命题逻辑的基本概念: CS2501-离散数学/2.1.命题逻辑的基本概念.md
        - 命题逻辑的等值和推演运算: CS2501-离散数学/2.2.命题逻辑的等值和推演运算.md
        - 谓词逻辑的基本概念: CS2501-离散数学/2.4.谓词逻辑的基本概念.md
        - 谓词逻辑的等值和推理演算: CS2501-离散数学/2.5.谓词逻辑的等值和推理演算.md
      - 集合论: 
        - 集合: CS2501-离散数学/3.9.集合.md
        - 关系: CS2501-离散数学/3.10.关系.md
        - 函数: CS2501-离散数学/3.11.函数.md
  - MARX1202-中国近现代史纲要:
      - MARX1202-中国近现代史纲要/index.md
      - 导言: MARX1202-中国近现代史纲要/导言.md
      - 第一章-进入近代后中华民族的磨难与抗争: MARX1202-中国近现代史纲要/第一章-进入近代后中华民族的磨难与抗争.md
      - 第二章-不同社会力量对国家出路的早期探索: MARX1202-中国近现代史纲要/第二章-不同社会力量对国家出路的早期探索.md
      - 第三章-辛亥革命与君主专制制度的终结: MARX1202-中国近现代史纲要/第三章-辛亥革命与君主专制制度的终结.md
      - 第四章-中国共产党成立和中国革命新局面: MARX1202-中国近现代史纲要/第四章-中国共产党成立和中国革命新局面.md
      - 第五章-中国革命的新道路: MARX1202-中国近现代史纲要/第五章-中国革命的新道路.md
      - 第六章-中华民族的抗日战争: MARX1202-中国近现代史纲要/第六章-中华民族的抗日战争.md
      - 第七章-为建立新中国而奋斗: MARX1202-中国近现代史纲要/第七章-为建立新中国而奋斗.md
      - 第八章-中华人民共和国的成立与中国社会主义建设道路的探索: MARX1202-中国近现代史纲要/第八章-中华人民共和国的成立与中国社会主义建设道路的探索.md
      - 第九章-改革开放与中国特色社会主义的开创和发展: MARX1202-中国近现代史纲要/第九章-改革开放与中国特色社会主义的开创和发展.md
      - 第十章-中国特色社会主义进入新时代: MARX1202-中国近现代史纲要/第十章-中国特色社会主义进入新时代.md
  - MARX1203-毛泽东思想和中国特色社会主义理论体系概论:
      - MARX1203-毛泽东思想和中国特色社会主义理论体系概论/index.md
      - 导论-马克思主义中国化的历史进程与理论成果: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/导论-马克思主义中国化的历史进程与理论成果.md
      - 第一章-毛泽东思想及其历史地位: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第一章-毛泽东思想及其历史地位.md
      - 第二章-新民主主义革命理论: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第二章-新民主主义革命理论.md
      - 第三章-社会主义改造理论: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第三章-社会主义改造理论.md
      - 第四章-社会主义建设道路初步探索: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第四章-社会主义建设道路初步探索.md
      - 第五章-中国特色社会主义理论体系的形成发展: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第五章-中国特色社会主义理论体系的形成发展.md
      - 第六章-邓小平理论: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第六章-邓小平理论.md
      - 第七章-三个代表重要思想: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第七章-三个代表重要思想.md
      - 第八章-科学发展观: MARX1203-毛泽东思想和中国特色社会主义理论体系概论/第八章-科学发展观.md
  - MARX1204-马克思主义基本原理:
      - MARX1204-马克思主义基本原理/index.md
      - 导论: MARX1204-马克思主义基本原理/导论.md
      - 第一章-世界的物质性及其发展规律: MARX1204-马克思主义基本原理/第一章-世界的物质性及其发展规律.md
      - 第二章-实践与认识及其发展规律: MARX1204-马克思主义基本原理/第二章-实践与认识及其发展规律.md
      - 第三章-人类社会及其发展规律: MARX1204-马克思主义基本原理/第三章-人类社会及其发展规律.md
      - 第四章-资本主义的本质及其规律: MARX1204-马克思主义基本原理/第四章-资本主义的本质及其规律.md
      - 第五章-资本主义的发展及其趋势: MARX1204-马克思主义基本原理/第五章-资本主义的发展及其趋势.md
      - 第六章-社会主义的发展及其规律: MARX1204-马克思主义基本原理/第六章-社会主义的发展及其规律.md
      - 第七章-共产主义崇高理想及其最终实现: MARX1204-马克思主义基本原理/第七章-共产主义崇高理想及其最终实现.md
  - MARX1208-思想道德与法治:
      - MARX1208-思想道德与法治/index.md
      - 绪论-担当复兴大任-成就时代新人: MARX1208-思想道德与法治/绪论-担当复兴大任-成就时代新人.md
      - 第一章-领悟人生真谛-把握人生方向: MARX1208-思想道德与法治/第一章-领悟人生真谛-把握人生方向.md
      - 第二章-追求远大理想-坚定崇高信念: MARX1208-思想道德与法治/第二章-追求远大理想-坚定崇高信念.md
      - 第三章-继承优良传统-弘扬中国精神: MARX1208-思想道德与法治/第三章-继承优良传统-弘扬中国精神.md
      - 第四章-明确价值要求践行价值准则: MARX1208-思想道德与法治/第四章-明确价值要求践行价值准则.md
      - 第五章-遵守道德规范-锤炼道德品格: MARX1208-思想道德与法治/第五章-遵守道德规范-锤炼道德品格.md
      - 第六章-学习法治思想-提升法治素养: MARX1208-思想道德与法治/第六章-学习法治思想-提升法治素养.md
  - MARX1219-习近平新时代中国特色社会主义思想概论:
      - MARX1219-习近平新时代中国特色社会主义思想概论/index.md
      - 导论-马克思主义中国化时代化新的飞跃: MARX1219-习近平新时代中国特色社会主义思想概论/导论-马克思主义中国化时代化新的飞跃.md
      - 第一章-新时代坚持和发展中国特色社会主义: MARX1219-习近平新时代中国特色社会主义思想概论/第一章-新时代坚持和发展中国特色社会主义.md
      - 第二章-以中国式现代化全面推进中华民族伟大复兴: MARX1219-习近平新时代中国特色社会主义思想概论/第二章-以中国式现代化全面推进中华民族伟大复兴.md
      - 第三章-坚持党的领导: MARX1219-习近平新时代中国特色社会主义思想概论/第三章-坚持党的领导.md
      - 第四章-坚持以人民为中心: MARX1219-习近平新时代中国特色社会主义思想概论/第四章-坚持以人民为中心.md
      - 第五章-全面深化改革开放: MARX1219-习近平新时代中国特色社会主义思想概论/第五章-全面深化改革开放.md
      - 第六章-推动高质量发展: MARX1219-习近平新时代中国特色社会主义思想概论/第六章-推动高质量发展.md
      - 第七章-社会主义现代化建设的教育科技人才战略: MARX1219-习近平新时代中国特色社会主义思想概论/第七章-社会主义现代化建设的教育科技人才战略.md
      - 第八章-发展全过程人民民主: MARX1219-习近平新时代中国特色社会主义思想概论/第八章-发展全过程人民民主.md
      - 第九章-全面依法治国: MARX1219-习近平新时代中国特色社会主义思想概论/第九章-全面依法治国.md
      - 第十章-建设社会主义文化强国: MARX1219-习近平新时代中国特色社会主义思想概论/第十章-建设社会主义文化强国.md
      - 第十一章-以保障和改善民生为重点加强社会建设: MARX1219-习近平新时代中国特色社会主义思想概论/第十一章-以保障和改善民生为重点加强社会建设.md
      - 第十二章-建设社会主义生态文明: MARX1219-习近平新时代中国特色社会主义思想概论/第十二章-建设社会主义生态文明.md
      - 第十三十五章-实现中华民族伟大复兴的重要保障: MARX1219-习近平新时代中国特色社会主义思想概论/第十三十五章-实现中华民族伟大复兴的重要保障.md
      - 第十六章-中国特色大国外交和推动构建人类命运共同体: MARX1219-习近平新时代中国特色社会主义思想概论/第十六章-中国特色大国外交和推动构建人类命运共同体.md
      - 第十七章-中国特色大国外交和推动构建人类命运共同体: MARX1219-习近平新时代中国特色社会主义思想概论/第十七章-中国特色大国外交和推动构建人类命运共同体.md
  - MATH1205-线性代数:
      - MATH1205-线性代数/index.md
      - 第一章-线性方程组与矩阵: MATH1205-线性代数/1.线性方程组与矩阵.md
      - 第二章-矩阵: MATH1205-线性代数/2.矩阵.md
      - 第三章-n维向量与线性方程组的结构: MATH1205-线性代数/3.n维向量与线性方程组的结构.md
      - 第四章-线性空间与线性变换: MATH1205-线性代数/4.线性空间与线性变换.md
      - 第五章-矩阵的相似对角化: MATH1205-线性代数/5.矩阵的相似对角化.md
      - 第六章-实二次型: MATH1205-线性代数/6.实二次型.md
  - MATH1207-概率统计:
      - MATH1207-概率统计/index.md
      - 第一章-随机事件和概率: MATH1207-概率统计/第一章-随机事件和概率.md
      - 第二章-随机变量及其分布: MATH1207-概率统计/第二章-随机变量及其分布.md
      - 第三章-多维随机变量及其分布: MATH1207-概率统计/第三章-多维随机变量及其分布.md
      - 第四章-随机变量的数字特征: MATH1207-概率统计/第四章-随机变量的数字特征.md
      - 第五章-大数定律和中心极限定理: MATH1207-概率统计/第五章-大数定律和中心极限定理.md
      - 第六章-数理统计的预备知识: MATH1207-概率统计/第六章-数理统计的预备知识.md
      - 第七章-参数估计: MATH1207-概率统计/第七章-参数估计.md
      - 第八章-假设检验: MATH1207-概率统计/第八章-假设检验.md
  - MIL1201-军事理论:
      - MIL1201-军事理论/index.md
      - 第一章-中国国防: MIL1201-军事理论/第一章-中国国防.md
      - 第二章-国家安全: MIL1201-军事理论/第二章-国家安全.md
      - 第三章-军事思想: MIL1201-军事理论/第三章-军事思想.md
      - 第四章-现代战争: MIL1201-军事理论/第四章-现代战争.md
      - 第五章-信息化装备: MIL1201-军事理论/第五章-信息化装备.md
  - NIS2301-网络空间安全导论:
      - NIS2301-网络空间安全导论/index.md
      - 第一章-网络空间安全概述: NIS2301-网络空间安全导论/第一章-网络空间安全概述.md
      - 第二章-密码学基础: NIS2301-网络空间安全导论/第二章-密码学基础.md
      - 第三章-网络安全基础: NIS2301-网络空间安全导论/第三章-网络安全基础.md
      - 第四章-系统安全基础: NIS2301-网络空间安全导论/第四章-系统安全基础.md
      - 第五章-内容安全基础: NIS2301-网络空间安全导论/第五章-内容安全基础.md
      - 第六章-应用安全基础: NIS2301-网络空间安全导论/第六章-应用安全基础.md
  - NIS2331-计算机组成与系统结构:
      - NIS2331-计算机组成与系统结构/index.md
      - Ch1-2-导论-计算机的演变和性能: NIS2331-计算机组成与系统结构/Ch1-2-导论-计算机的演变和性能.md
      - Ch3-计算机功能和互连的顶层视图: NIS2331-计算机组成与系统结构/Ch3-计算机功能和互连的顶层视图.md
      - Ch4-Cache存储器: NIS2331-计算机组成与系统结构/Ch4-Cache存储器.md
      - Ch5-内部存储器: NIS2331-计算机组成与系统结构/Ch5-内部存储器.md
      - Ch6-外部存储器: NIS2331-计算机组成与系统结构/Ch6-外部存储器.md
      - Ch7-输入输出: NIS2331-计算机组成与系统结构/Ch7-输入输出.md
      - Ch9-计算机算术: NIS2331-计算机组成与系统结构/Ch9-计算机算术.md
      - Ch10-指令集特征和功能: NIS2331-计算机组成与系统结构/Ch10-指令集特征和功能.md
      - Ch11-指令集寻址方式和指令模式: NIS2331-计算机组成与系统结构/Ch11-指令集寻址方式和指令模式.md
      - Ch12-CPU结构和功能: NIS2331-计算机组成与系统结构/Ch12-CPU结构和功能.md
      - Ch13-精简指令集计算机RISC: NIS2331-计算机组成与系统结构/Ch13-精简指令集计算机RISC.md
      - Ch14-指令级并行性和超标量处理器: NIS2331-计算机组成与系统结构/Ch14-指令级并行性和超标量处理器.md
      - Ch17-并行处理: NIS2331-计算机组成与系统结构/Ch17-并行处理.md
  - NIS2333-抽象代数:
      - NIS2333-抽象代数/index.md
      - 解题范式: NIS2333-抽象代数/解题范式.md
      - 第一章-群: NIS2333-抽象代数/第一章-群.md
      - 第二章-环: NIS2333-抽象代数/第二章-环.md
  - NIS2334-操作系统原理:
      - NIS2334-操作系统原理/index.md
      - 操作系统概述: NIS2334-操作系统原理/1.操作系统概述.md
      - 内存管理: NIS2334-操作系统原理/2.内存管理.md
      - 进程管理: NIS2334-操作系统原理/3.进程管理.md
      - 进程通信: NIS2334-操作系统原理/4.进程通信.md
      - 设备管理: NIS2334-操作系统原理/5.设备管理.md
      - 外部存储: NIS2334-操作系统原理/6.外部存储.md
      - 文件系统: NIS2334-操作系统原理/7.文件系统.md
      - 操作系统安全: NIS2334-操作系统原理/8.操作系统安全.md
  - NIS2336-编译原理:
      - NIS2336-编译原理/index.md
      - Ch1-Intro: NIS2336-编译原理/Ch1-Intro.md
      - Ch2-Syntax-Definition: NIS2336-编译原理/Ch2-Syntax-Definition.md
      - Ch3-Scanning: NIS2336-编译原理/Ch3-Scanning.md
      - Ch4-Parsing: NIS2336-编译原理/Ch4-Parsing.md
  - NIS2337-信息论基础:
      - NIS2337-信息论基础/index.md
      - 第一章-绪论: NIS2337-信息论基础/第一章-绪论.md
      - 第二章-信源与信息熵: NIS2337-信息论基础/第二章-信源与信息熵.md
      - 第二章补充-微分熵: NIS2337-信息论基础/第二章补充-微分熵.md
      - 第三章-信道与信道容量: NIS2337-信息论基础/第三章-信道与信道容量.md
      - 第四章-信息率失真函数: NIS2337-信息论基础/第四章-信息率失真函数.md
      - 第五章-信源编码: NIS2337-信息论基础/第五章-信源编码.md
      - 第五章补充-无失真信源编码: NIS2337-信息论基础/第五章补充-无失真信源编码.md
      - 第六章-信道编码: NIS2337-信息论基础/第六章-信道编码.md
      - 第六章补充-信道编码: NIS2337-信息论基础/第六章补充-信道编码.md
  - NIS3301-系统安全:
      - NIS3301-系统安全/index.md
      - 系统安全概述: NIS3301-系统安全/1.系统安全概述.md
      - 操作系统安全机制: NIS3301-系统安全/2.操作系统安全机制.md
      - Windows-操作系统安全: NIS3301-系统安全/3.Windows-操作系统安全.md
      - Linux-操作系统安全: NIS3301-系统安全/4.Linux-操作系统安全.md
      - 移动操作系统安全: NIS3301-系统安全/5.移动操作系统安全.md
      - 网络安全: NIS3301-系统安全/6.网络安全.md
      - 数据流分析: NIS3301-系统安全/7.数据流分析.md
      - 人工智能系统安全: NIS3301-系统安全/8.人工智能系统安全.md
      - 数据库安全: NIS3301-系统安全/9.数据库安全.md
      - 密码学基础: NIS3301-系统安全/10.密码学基础.md
      - 硬件安全: NIS3301-系统安全/11.硬件安全.md
  - NIS3329-初等数论与抽象代数:
      - NIS3329-初等数论与抽象代数/index.md
      - Ch1-Divisibility: NIS3329-初等数论与抽象代数/Chapter-1-Divisibility.md
      - Ch2-Congruences: NIS3329-初等数论与抽象代数/Chapter-2-Congruences.md
      - Ch3-Primitive-roots-and-discrete-logarithm: NIS3329-初等数论与抽象代数/Chapter-3-Primitive-roots-and-discrete-logarithm.md
      - Ch4-Quadratic-Residues: NIS3329-初等数论与抽象代数/Chapter-4-Quadratic-Residues.md
      - Ch5-Polynomials: NIS3329-初等数论与抽象代数/Chapter-5-Polynomials.md
      - Ch6-Finite-fields: NIS3329-初等数论与抽象代数/Chapter-6-Finite-fields.md
  - NIS3351-数据库原理及安全:
      - NIS3351-数据库原理及安全/index.md
      - 第一章-数据库系统概论: NIS3351-数据库原理及安全/第一章-数据库系统概论.md
      - 第二章-关系模型和关系运算理论: NIS3351-数据库原理及安全/第二章-关系模型和关系运算理论.md
      - 第三章-关系规范化基础: NIS3351-数据库原理及安全/第三章-关系规范化基础.md
      - 第四章-结构查询语言SQL: NIS3351-数据库原理及安全/第四章-结构查询语言SQL.md
      - 第五章-数据库设计: NIS3351-数据库原理及安全/第五章-数据库设计.md
      - 第六章-数据库安全: NIS3351-数据库原理及安全/第六章-数据库安全.md
  - NIS3352-现代密码学Ⅱ:
      - NIS3352-现代密码学Ⅱ/index.md
      - Ch1-密码学中的可证明安全理论: NIS3352-现代密码学Ⅱ/Ch1-密码学中的可证明安全理论.md
      - Ch2-基于身份和属性的密码: NIS3352-现代密码学Ⅱ/Ch2-基于身份和属性的密码.md
      - Ch3-后量子密码: NIS3352-现代密码学Ⅱ/Ch3-后量子密码.md
      - Ch4-零知识证明: NIS3352-现代密码学Ⅱ/Ch4-零知识证明.md
  - NIS3355-算法计算复杂度分析:
      - NIS3355-算法计算复杂度分析/index.md
      - 算法计算复杂度分析概论: NIS3355-算法计算复杂度分析/1.算法计算复杂度分析概论.md
      - 顺序算法: NIS3355-算法计算复杂度分析/2.顺序算法.md
      - 顺序算法图算法: NIS3355-算法计算复杂度分析/3.顺序算法图算法.md
      - 分布式算法: NIS3355-算法计算复杂度分析/4.分布式算法.md
  - NIS3364-计算机通信网络:
      - NIS3364-计算机通信网络/index.md
      - 计算机网络概述: NIS3364-计算机通信网络/1.计算机网络概述.md
      - 物理层: NIS3364-计算机通信网络/2.物理层.md
      - 数据链路层: NIS3364-计算机通信网络/3.数据链路层.md
      - 网络层: NIS3364-计算机通信网络/4.网络层.md
      - 传输层: NIS3364-计算机通信网络/5.传输层.md
      - 应用层: NIS3364-计算机通信网络/6.应用层.md
      - 无线网络和移动网络: NIS3364-计算机通信网络/7.无线网络和移动网络.md
  - NIS3365-现代密码学:
      - NIS3365-现代密码学/index.md
      - 密码学与计算机安全: NIS3365-现代密码学/1.密码学与计算机安全.md
      - 古典密码算法: NIS3365-现代密码学/2.古典密码算法.md
      - 序列密码: NIS3365-现代密码学/3.序列密码.md
      - 分组密码: NIS3365-现代密码学/4.分组密码.md
      - 公钥密码: NIS3365-现代密码学/5.公钥密码.md
      - 认证与哈希函数: NIS3365-现代密码学/6.认证与哈希函数.md
      - 数字签名算法: NIS3365-现代密码学/7.数字签名算法.md
  - NIS3368-安全模型开发及安全编程:
      - NIS3368-安全模型开发及安全编程/index.md
      - Lab1-HTML: NIS3368-安全模型开发及安全编程/Lab1-HTML.md
      - Lab2-CSS: NIS3368-安全模型开发及安全编程/Lab2-CSS.md
      - Lab3-JavaScript: NIS3368-安全模型开发及安全编程/Lab3-JavaScript.md
      - Lab4-MySQL: NIS3368-安全模型开发及安全编程/Lab4-MySQL.md
  - PHY1253-量子力学:
      - PHY1253-量子力学/index.md
      - 量子力学基础: PHY1253-量子力学/1.量子力学基础.md
      - 量子力学入门: PHY1253-量子力学/2.量子力学入门.md
      - 量子力学深入: PHY1253-量子力学/3.量子力学深入.md
      - 量子力学应用: PHY1253-量子力学/4.量子力学应用.md
